### ISSUE TITLE
Wave et love2d 11.1

### ISSUE THREAD

**Issue by oMiCid00** [Ulydev/wave#3]
Hello,

J'obtiens une erreur lorsqu'un son est appelé (suite a l'appuie d'une touche) sur mon projet sur love2d 11.1, une idée ? 
merci d'avance !

`Error

lib/wave.lua:74: bad argument #2 to 'newSource' (string expected, got nil)

Traceback

[C]: in function 'newSource'
lib/wave.lua:74: in function 'play'
include/player.lua:69: in function 'keypressed'
scenes/game.lua:123: in function <scenes/game.lua:110>
[C]: in function 'xpcall'`

**Comment by Ulydev** [comment]
Salut, merci pour le report ! Je ne sais pas d’où cela vient, il y a dû y avoir des changements dans l’API lors du passage à la version 11. Je ne peux rien promettre (c’est la période d’examens en ce moment), mais je vais essayer de régler ça si j’ai un peu de temps. Sinon, un PR est la bienvenue ;-)

**Comment by Ulydev** [comment]
Hello, désolé pour le retard, j'ai enfin eu le temps de regarder. Finalement c'était pas grand-chose, juste le paramètre par défaut qui a été supprimé dans LÖVE 11. Je n'ai testé que les démos, si il y a un autre problème n'hésite pas à me le faire savoir :-) à+
