### ISSUE TITLE
Calling setBPM() results in a nil value

### ISSUE THREAD

**Issue by kfjustis** [Ulydev/wave#4]
**Example of the error:**
`Error: wave/wave.lua:184: attempt to index local 'self' (a nil value)
stack traceback:
        [string "boot.lua"]:777: in function '__newindex'
        wave/wave.lua:184: in function 'onBeat'
        wave/wave.lua:527: in function 'updateBeat'
        wave/wave.lua:488: in function 'update'
        main.lua:12: in function 'update'
        [string "boot.lua"]:612: in function <[string "boot.lua"]:594>
        [C]: in function 'xpcall'`

**Minimum code example:**
````
local wave = require 'wave.wave'

function love.load()
    music = wave:newSource('/wave/music.wav', 'stream')
    music:parse()
    music:setIntensity(20)
    music:setBPM(200)
    music:play()
end

function love.update(dt)
    music:update(dt)
end

function love.draw(dt)
    love.graphics.circle('fill', 400, 300, 100 + music:getEnergy()*20)
end
````
Either removing the line that calls setBPM() in love.load or implementing an empty onBeat() callback such as:
```
music:onBeat(function()
    end)
```
prevents the nil value error from happening.

Also, even with implementing the empty onBeat() callback, I could not get setBPM() to actually change the BPM of the music.

**Expected behavior:** Calling setBPM() should change the BPM of the music as expected and should not result in nil value error.

Otherwise, this library is awesome! Thanks for making it.

**Comment by zorggn** [comment]
I don't think setBPM allows you to speed up / slow down the speed of the sound; it's just a helper function if you already know the BPM and don't need to detect it.

**Comment by kfjustis** [comment]
Ah, gotcha. I'll close this then.
